### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by itxubfmh** [ryannair05/ApolloAPI#1]
Thank you so much for your contribution to reburn Apollo. 

The redirect uri must not be set to 'apollo://reddit-oauth', URI scheme must be one of:http,https per Reddit popup message
Authentication will fail if you try to set the redirect URI to https://reddit-oauth or http://reddit-oauth.
Please advise how to fix this?

Error message:
There was an error trying to connect with your reddit account

You got here because a third-party application wanted to authorize connecting with your reddit account. However an unknown error occurred, please see details below. Please try refreshing the page or coming back later.
Error: Error fetching oauth client
Error: Error fetching oauth client
    at requestOauthApp (/src/packages/applications/monolith/bin/index.cjs:145599:16)
    at async Proxy.renderAfterQuery (/src/packages/applications/monolith/bin/index.cjs:185751:26)
    at async /src/packages/applications/monolith/bin/index.cjs:142702:21
    at async withLocalSpanGeneratorAsync (/src/packages/applications/monolith/bin/index.cjs:136312:18)
    at async Proxy.<anonymous> (/src/packages/applications/monolith/bin/index.cjs:142700:17)
    at async renderFeature (/src/packages/applications/monolith/bin/index.cjs:142972:21)
    at async renderFeatureTree (/src/packages/applications/monolith/bin/index.cjs:143117:5)
    at async StreamingRenderer.renderAsGenerator (/src/packages/applications/monolith/bin/index.cjs:143212:13)

**Comment by Ijustplaymc** [comment]
Select application, not web app

**Comment by itxubfmh** [comment]
Apologize for this,it works finally.Thanks a lot!
